name: sahanddriver
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  url_launcher: ^5.4.11
  pl_notifications: ^0.0.3+1
  dio_retry: ^0.1.9-beta
  wakelock: ^0.1.4+1
  progress_dialog: ^1.2.4
  jalali_date: ^0.1.5
  cached_network_image: ^2.2.0+1
  audioplayers: ^0.15.1
  rflutter_alert: ^1.0.3
  dotted_border: ^1.0.5
  rnd: ^0.1.0
  location: ^3.0.2
  flutter_map: ^0.9.0
  shared_preferences: ^0.5.7+1
  fluttertoast: ^4.0.1
  socket_io_client: ^0.9.10
  dio: 3.0.9
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_rating_bar: ^3.0.1+1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/splash.png
   - assets/images/profile.png
   - assets/images/chart.png
   - assets/images/driveclub.png
   - assets/images/history.png
   - assets/images/off.png
   - assets/images/profileic.png
   - assets/images/setting.png
   - assets/images/support.png
   - assets/images/wallet.png
   - assets/images/carprof.png
   - assets/images/card.png
   - assets/images/mabda.png
   - assets/images/maghsad.png
   - assets/images/time.png
   - assets/images/coin.png
   - assets/images/navibefire.png
   - assets/images/logo.png
   - assets/images/plus.png
   - assets/images/inc.png
   - assets/images/ic_launcher.png
   - assets/images/headsetman.png
   - assets/images/mapicon.png
   - assets/images/mabda_ic.png
   - assets/images/maghsad_ic.png
   - assets/images/drivermarker.png
   - assets/audio/newride.mp3
   - assets/audio/ride_accepted.mp3
   - assets/audio/ride_cancelled_by_passenger.mp3
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  flutter:
    fonts:
      - family: IRANSans
        fonts:
          - asset: assets/fonts/IRANSans.ttf
            style: italic

    uses-material-design: true
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
